---
  - name: EOEPCA local development environment
    hosts: all
    become: yes

    roles:
    - geerlingguy.git
    - geerlingguy.java
    - reallyenglish.git
    - gantsign.intellij

    vars:
      git_additional_packages:
        - "{% if ansible_os_family == 'FreeBSD' %}gitflow{% elif ansible_os_family == 'OpenBSD' %}git-cvs{% elif ansible_os_family == 'RedHat' %}git-cvs{% else %}git-flow{% endif %}"
